### ISSUE TITLE
pm-updatestatus command does not exist in earlier versions of drush

### ISSUE THREAD

**Issue by jbickar** [SU-SWS/erus#2]
https://github.com/SU-SWS/erus/blob/7.x-1.x-dev/drush/erus.drush.inc#L44

drush 5.4 gives the following error when running "drush eup" : 

```
The drush command 'pm-updatestatus' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed[error]
new extensions.
```

**Comment by sherakama** [comment]
Not sure if this process will work on 5.4 yet.

In the interim I have added a major version check for 6 or greater. see: https://github.com/SU-SWS/erus/commit/3fc9a5032a48fcc60c45264d20c1698bfdeec8c7

**Comment by jbickar** [comment]
I think it's fine to set this to won't fix, or rely on the major version check for > 6, just wanted to note this when I ran into it.

**Comment by kreynen** [comment]
Is this still something that needs to be open since both Drush 5 and 6 are no longer officially supported?  http://docs.drush.org/en/master/install/#drupal-compatibility

**Comment by sherakama** [comment]
Proof that sometimes if you wait long enough, the problem fixes itself.

**Comment by jbickar** [comment]
Patience pays off for the second time today.
